version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Stockholm"
    commit-message:
      prefix: "chore(deps)"
    groups:
      bun-production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      bun-development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Stockholm"
    commit-message:
      prefix: "chore(deps)"
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Stockholm"
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
