<script lang="ts">
	import { createQuery } from "@tanstack/svelte-query";
	import { Alert, AlertDescription, AlertTitle, Badge, Button, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, Field, FieldGroup, FieldLabel, Input, Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue, Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/svelte";
	import ArgoConnectionSettings from "@/app/svelte/ArgoConnectionSettings.svelte";
	import { createTauriClient, getArgoApplicationInspector, getArgoApplicationResources, getArgoConnectionStatus, getArgoResourceComparison, preflightArgoOperation, runArgoOperation } from "@/lib/tauri";
	import { settingsStore } from "@/lib/settings-store";
	import type { ArgoManagedResource, ArgoOperationAction, ArgoOperationPreflight, ArgoOperationRequest, ArgoResourceAction, ResourceSummary } from "@/lib/types";
	import type { WorkspaceReadContext } from "@/lib/workspaceReadContext";

	let { resourceSummary, workspaceReadContext, active }: { resourceSummary: ResourceSummary; workspaceReadContext: WorkspaceReadContext; active: boolean } = $props();
	const client = createTauriClient();
	const clusterContext = $derived(workspaceReadContext.clusterContext);
	const workspaceId = $derived(workspaceReadContext.workspaceId);
	const kubeconfigEnvVar = $derived(workspaceReadContext.kubeconfigSourceKey);
	let transport = $state<"connected" | "kubernetes">("kubernetes");
	let connectionId = $state("");
	let resource = $state<ArgoManagedResource | null>(null);
	let tab = $state("overview");
	let connectionSettingsOpen = $state(false);
	let operationError = $state<string | null>(null);
	let pendingAction = $state<ArgoOperationAction | null>(null);
	let pendingPreflight = $state<ArgoOperationPreflight | null>(null);
	let confirmationName = $state("");
	let revision = $state("");
	let prune = $state(false);
	let dryRun = $state(false);
	let force = $state(false);
	let selectedResources = $state<ArgoManagedResource[]>([]);
	let selectedHistoryId = $state<number | null>(null);
	let resourceAction = $state("sync");
	let selectedResourceAction = $state<ArgoResourceAction | null>(null);
	let resourceActionParameters = $state<Record<string, string>>({});
	const application = $derived({ name: resourceSummary.name, namespace: resourceSummary.namespace, project: null, resourceVersion: null, uid: null, apiVersion: resourceSummary.apiVersion ?? "argoproj.io/v1alpha1", context: clusterContext, workspaceId });
	const matchingProfiles = $derived($settingsStore.argoProfiles.filter((profile) => profile.clusterContext === clusterContext && (!profile.workspaceId || profile.workspaceId === workspaceId)));
	const statuses = createQuery(() => ({ queryKey: ["argo-connection-status", clusterContext, workspaceId, matchingProfiles.map((profile) => profile.id).join(",")], queryFn: () => Promise.all(matchingProfiles.map(async (profile) => [profile.id, await getArgoConnectionStatus(client, profile.id)] as const)), enabled: active && matchingProfiles.length > 0, staleTime: 5_000 }));
	const selectedStatus = $derived(statuses.data?.find(([id]) => id === connectionId)?.[1]);
	const request = $derived({ clusterContext, kubeconfigEnvVar, connectionId: transport === "connected" ? connectionId : undefined, transport, application, redactSecrets: $settingsStore.redactSecrets });
	const inspector = createQuery(() => ({ queryKey: ["argo-inspector", clusterContext, transport, connectionId, resourceSummary.namespace ?? "", resourceSummary.name, $settingsStore.redactSecrets], queryFn: () => getArgoApplicationInspector(client, request), enabled: active && (transport === "kubernetes" || Boolean(connectionId)), gcTime: $settingsStore.redactSecrets ? undefined : 0 }));
	const resources = createQuery(() => ({ queryKey: ["argo-resources", clusterContext, transport, connectionId, resourceSummary.namespace ?? "", resourceSummary.name, $settingsStore.redactSecrets], queryFn: () => getArgoApplicationResources(client, request), enabled: active && (transport === "kubernetes" || Boolean(connectionId)), gcTime: $settingsStore.redactSecrets ? undefined : 0 }));
	const comparison = createQuery(() => ({ queryKey: ["argo-comparison", clusterContext, transport, connectionId, resourceSummary.namespace ?? "", resourceSummary.name, resource?.group ?? "", resource?.kind ?? "", resource?.namespace ?? "", resource?.name ?? "", $settingsStore.redactSecrets], queryFn: () => getArgoResourceComparison(client, { ...request, resource: resource! }), enabled: active && Boolean(resource) && (transport === "kubernetes" || Boolean(connectionId)), gcTime: $settingsStore.redactSecrets ? undefined : 0 }));
	const resourceVersion = $derived(inspector.data?.application.resourceVersion ?? null);

	function json(value: unknown) { return value === undefined || value === null ? "Unavailable" : JSON.stringify(value, null, 2); }
	function clearComparison() { resource = null; selectedResources = []; selectedHistoryId = null; resourceAction = ""; selectedResourceAction = null; resourceActionParameters = {}; pendingAction = null; pendingPreflight = null; confirmationName = ""; operationError = null; revision = ""; prune = false; dryRun = false; force = false; }
	function setTransport(value: string) { transport = value === "connected" ? "connected" : "kubernetes"; clearComparison(); }
	function setConnection(value: string) { connectionId = value; transport = "connected"; clearComparison(); }
	function operation(action: ArgoOperationAction): ArgoOperationRequest { return { connectionId: transport === "connected" ? connectionId : null, transport, application, action, revision: revision || null, resources: action === "sync" ? selectedResources : action === "resourceAction" && resource ? [resource] : [], prune, dryRun, force, historyId: selectedHistoryId, resourceAction: action === "resourceAction" ? resourceAction : null, resourceActionParameters: action === "resourceAction" ? resourceActionParameters : null, resourceVersion, clusterContext, kubeconfigEnvVar }; }
	function selectResourceAction(action: ArgoResourceAction) { if (action.disabled) return; resourceAction = action.name; selectedResourceAction = action; resourceActionParameters = Object.fromEntries((action.params ?? []).map((param) => [param.name, param.defaultValue ?? ""])); }
	async function refresh() { operationError = null; try { const preflight = await preflightArgoOperation(client, operation("refresh")); if (!preflight.allowed || !preflight.preflightToken || !preflight.resolvedRequest) throw new Error(preflight.reason ?? "Refresh unavailable"); await runArgoOperation(client, { ...preflight.resolvedRequest, preflightToken: preflight.preflightToken }); await Promise.all([inspector.refetch(), resources.refetch()]); } catch (error) { operationError = error instanceof Error ? error.message : String(error); } }
	async function requestOperation(action: ArgoOperationAction) { if (action === "resourceAction" && selectedResourceAction?.params?.some((param) => param.required && !resourceActionParameters[param.name]?.trim())) { operationError = "Fill required resource action parameters"; return; } operationError = null; pendingPreflight = null; try { const preflight = await preflightArgoOperation(client, operation(action)); if (!preflight.allowed || !preflight.preflightToken || !preflight.resolvedRequest) throw new Error(preflight.reason ?? "Operation unavailable"); pendingAction = action; pendingPreflight = preflight; confirmationName = ""; } catch (error) { operationError = error instanceof Error ? error.message : String(error); } }
	async function confirmOperation() { if (!pendingAction || !pendingPreflight?.resolvedRequest || !pendingPreflight.preflightToken || confirmationName !== resourceSummary.name) return; try { await runArgoOperation(client, { ...pendingPreflight.resolvedRequest, preflightToken: pendingPreflight.preflightToken }); pendingAction = null; pendingPreflight = null; await Promise.all([inspector.refetch(), resources.refetch()]); } catch (error) { operationError = error instanceof Error ? error.message : String(error); } }
</script>

<div class="flex flex-col gap-3">
	<div class="flex flex-wrap items-center gap-2"><Select value={transport} onValueChange={setTransport}><SelectTrigger class="w-56"><SelectValue placeholder="Choose access path" /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="kubernetes">Kubernetes fallback</SelectItem><SelectItem value="connected">Connected Argo CD profile</SelectItem></SelectGroup></SelectContent></Select>{#if transport === "connected"}<Select value={connectionId} onValueChange={setConnection}><SelectTrigger class="w-56"><SelectValue placeholder="Select connected profile" /></SelectTrigger><SelectContent><SelectGroup>{#each matchingProfiles as profile}<SelectItem value={profile.id}>{profile.url}</SelectItem>{/each}</SelectGroup></SelectContent></Select>{/if}<Button size="sm" type="button" variant="outline" onclick={() => (connectionSettingsOpen = true)}>Connection settings</Button></div>
	{#if transport === "kubernetes"}<Alert><AlertTitle>Kubernetes-authorized fallback</AlertTitle><AlertDescription>Argo RBAC is not evaluated.</AlertDescription></Alert>{:else if connectionId && !selectedStatus?.connected}<Alert variant="destructive"><AlertTitle>Profile not connected</AlertTitle><AlertDescription>{selectedStatus?.unavailableReason ?? "Reconnect profile in connection settings."}</AlertDescription></Alert>{/if}
	{#if operationError}<Alert variant="destructive"><AlertTitle>Operation failed</AlertTitle><AlertDescription>{operationError}</AlertDescription></Alert>{/if}
	<div class="flex flex-wrap gap-2"><Button size="sm" type="button" onclick={refresh}>Refresh</Button><Button size="sm" type="button" variant="outline" onclick={() => requestOperation("sync")}>Sync</Button><Button size="sm" type="button" variant="outline" onclick={() => requestOperation("retry")}>Retry</Button>{#if transport === "connected"}<Button size="sm" type="button" variant="outline" onclick={() => requestOperation("rollback")}>Rollback</Button><Button size="sm" type="button" variant="destructive" onclick={() => requestOperation("terminate")}>Terminate</Button>{#if resource}{#each comparison.data?.availableActions ?? [] as action}<Button size="sm" type="button" variant="outline" onclick={() => selectResourceAction(action)} disabled={action.disabled}>Action {action.name}</Button>{/each}{/if}{/if}</div>
	<FieldGroup class="gap-2"><Field><FieldLabel>Revision</FieldLabel><Input bind:value={revision} placeholder="Optional revision" /></Field><Field orientation="horizontal"><input type="checkbox" bind:checked={prune} /> Prune</Field><Field orientation="horizontal"><input type="checkbox" bind:checked={dryRun} /> Dry run</Field><Field orientation="horizontal"><input type="checkbox" bind:checked={force} /> Force</Field></FieldGroup>
	<Tabs value={tab} onValueChange={(value: string) => (tab = value)}><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="resources">Resources</TabsTrigger><TabsTrigger value="history">History</TabsTrigger><TabsTrigger value="diff">Diff</TabsTrigger></TabsList>
		<TabsContent value="overview" class="flex flex-col gap-2"><Badge variant={inspector.data?.connected ? "secondary" : "outline"}>{inspector.data?.connected ? "Argo CD API" : "Application CRD"}</Badge><pre class="max-h-[45vh] overflow-auto rounded-md border p-3">{json(inspector.data?.status)}</pre></TabsContent>
		<TabsContent value="resources"><div class="flex flex-col gap-2">{#each resources.data ?? [] as item}<Button variant={resource === item ? "secondary" : "outline"} class="w-full justify-start" onclick={() => { resource = item; tab = "diff"; }}><span>{item.kind ?? "Resource"} {item.namespace ? `${item.namespace}/` : ""}{item.name ?? "unknown"}</span><span class="ml-auto flex gap-1"><Badge variant="outline">{item.status ?? "Unknown"}</Badge><Badge variant="outline">{item.health ?? "Unknown"}</Badge>{#if item.hook}<Badge variant="secondary">Hook</Badge>{/if}{#if item.requiresPruning}<Badge variant="destructive">Prune</Badge>{/if}</span></Button>{:else}<p class="text-muted-foreground">No managed resources reported.</p>{/each}</div></TabsContent>
		<TabsContent value="history"><div class="flex flex-col gap-2">{#each inspector.data?.history ?? [] as entry}<Button variant={selectedHistoryId === entry.id ? "secondary" : "outline"} class="h-auto justify-start text-left" onclick={() => (selectedHistoryId = entry.id ?? null)}><span><strong>{(entry.revision ?? entry.revisions.join(", ")) || "Unknown revision"}</strong><br />{entry.deployedAt ?? "No deployment timestamp"}{#if entry.revisions.length > 1}<br />Sources: {entry.revisions.join(", ")}{/if}</span></Button>{:else}<p class="text-muted-foreground">No history reported.</p>{/each}</div></TabsContent>
		<TabsContent value="diff" class="flex flex-col gap-2">{#if resource}<p class="text-muted-foreground">{comparison.data?.provenance ?? (comparison.data?.exact ? "Argo CD API comparison" : "Exact comparison unavailable")}</p><pre class="max-h-[45vh] overflow-auto rounded-md border p-3">Target\n{json(comparison.data?.targetState)}\n\nLive\n{json(comparison.data?.liveState)}\n\nNormalized live\n{json(comparison.data?.normalizedLiveState)}\n\nPredicted\n{json(comparison.data?.predictedLiveState)}</pre>{:else}<p class="text-muted-foreground">Select a resource to compare target and live state.</p>{/if}</TabsContent>
	</Tabs>
	{#if selectedResourceAction}<FieldGroup class="gap-2">{#each selectedResourceAction.params ?? [] as parameter}<Field><FieldLabel>{parameter.name}{parameter.required ? " *" : ""}</FieldLabel><Input value={resourceActionParameters[parameter.name] ?? ""} oninput={(event: Event) => resourceActionParameters = { ...resourceActionParameters, [parameter.name]: (event.currentTarget as HTMLInputElement).value }} /></Field>{/each}<Button size="sm" type="button" onclick={() => requestOperation("resourceAction")}>Run {selectedResourceAction.name}</Button></FieldGroup>{/if}
</div>

<Dialog open={connectionSettingsOpen} onOpenChange={(value: boolean) => (connectionSettingsOpen = value)}><DialogContent class="max-w-2xl"><DialogHeader><DialogTitle>Argo CD connection settings</DialogTitle><DialogDescription>Manage connection profiles for this workspace.</DialogDescription></DialogHeader><ArgoConnectionSettings {clusterContext} {workspaceId} {kubeconfigEnvVar} /></DialogContent></Dialog>
<Dialog open={pendingAction !== null} onOpenChange={(value: boolean) => { if (!value) { pendingAction = null; pendingPreflight = null; } }}><DialogContent><DialogHeader><DialogTitle>Confirm {pendingAction}</DialogTitle><DialogDescription>Target: {resourceSummary.namespace ?? "default"}/{resourceSummary.name}. Scope: {transport === "connected" ? "Argo CD server" : `Kubernetes context ${clusterContext}`}. This operation may change application state.</DialogDescription></DialogHeader>{#if pendingPreflight?.resolvedRequest}<pre class="max-h-48 overflow-auto rounded border p-2 text-xs">{json(pendingPreflight.resolvedRequest)}</pre>{/if}<Field><FieldLabel>Type application name to confirm</FieldLabel><Input bind:value={confirmationName} /></Field><div class="flex justify-end gap-2"><Button variant="outline" onclick={() => { pendingAction = null; pendingPreflight = null; }}>Cancel</Button><Button disabled={confirmationName !== resourceSummary.name} onclick={confirmOperation}>Confirm</Button></div></DialogContent></Dialog>
